CREATE TABLE   noteful_notes (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  content TEXT,
  folder_id INTEGER REFERENCES noteful_folders(id) NOT NULL,
  date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);